version: "2"
services:
  web:
    build: .
    working_dir: /usr/src/app
    volumes:
      - "./:/usr/src/app"
    command: "bash -c 'npm run dev'"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"